; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Monitor settings
monitor_speed = 115200
monitor_filters = 
	default
	time
monitor_dtr = 0
monitor_rts = 0

; Build settings
build_flags = 
	-DCORE_DEBUG_LEVEL=0
	-DBOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue

; Library dependencies
lib_deps = 
	ezButton@^1.0.6
	adafruit/Adafruit SSD1351 library@^1.3.2
	adafruit/Adafruit GFX Library@^1.11.11
	robtillaart/ADS1X15@^0.5.1
	robtillaart/DAC8571@^0.1.2

; Upload settings  
upload_speed = 921600

; Auto-increment version on build
extra_scripts = pre:increment_version.py
